/**
 * The avatar shown on the landing page.
 *
 * Generated by the same engine that makes a user's avatar, rather than a static
 * asset checked into the repository. A marketing page for a 3D tool showing a
 * hand-made model would be a small lie, and this way the hero can never drift
 * out of step with what the product actually produces.
 *
 * Generation takes well under a second, and the result is memoised for the
 * lifetime of the process and cached hard at the edge, so it happens about once.
 */

import { NextResponse } from "next/server";
import { buildAvatarGlb } from "@/lib/avatar-engine/build-avatar-glb";
import { buildHumanoid } from "@/lib/avatar-engine/geometry/humanoid";
import { buildSkeleton } from "@/lib/avatar-engine/geometry/skeleton";
import { bodyParamsSchema, faceParamsSchema } from "@/lib/avatar-engine/params";
import { renderAvatarAtlasPng } from "@/lib/avatar-engine/texture/atlas";
import { garmentTemplate } from "@/lib/clothing/templates";

export const dynamic = "force-static";
export const revalidate = 86400;

let cached: Uint8Array | null = null;

async function buildDemo(): Promise<Uint8Array> {
  const body = bodyParamsSchema.parse({
    heightCm: 178,
    build: 0.44,
    shoulderWidth: 0.62,
    chest: 0.52,
    waist: 0.4,
    muscle: 0.58,
    legLength: 0.55,
  });

  const face = faceParamsSchema.parse({
    skinTone: "#b57f5e",
    hairColor: "#241a15",
    eyeColor: "#3d5a80",
    hairStyle: "short",
  });

  const skeleton = buildSkeleton(body);
  const mesh = buildHumanoid(body, face, skeleton);
  const texture = await renderAvatarAtlasPng({ face });

  const garments = ["long-sleeve", "jeans", "sneakers"]
    .map((id) => garmentTemplate(id))
    .filter((template) => template !== undefined)
    .map((template) => ({
      name: template.id,
      mesh: template.build({ body, skeleton }),
      colorHex: template.defaultColor,
    }));

  return buildAvatarGlb({ mesh, skeleton, texture, garments, name: "Incarnatrun demo" });
}

export async function GET() {
  cached ??= await buildDemo();

  return new NextResponse(new Uint8Array(cached), {
    headers: {
      "Content-Type": "model/gltf-binary",
      "Content-Length": String(cached.byteLength),
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=604800",
    },
  });
}
