"use client";

import * as React from "react";
import dynamic from "next/dynamic";
import { Badge } from "@/components/ui/primitives";

/*
  The viewer is loaded on the client only. three.js and its loaders are a large
  bundle with no server-rendered output worth having, and rendering a canvas on
  the server produces nothing but a hydration warning.
*/
const AvatarViewer = dynamic(
  () => import("@/components/three/avatar-viewer").then((m) => m.AvatarViewer),
  {
    ssr: false,
    loading: () => (
      <div className="grid aspect-[4/5] w-full place-items-center rounded-[4px] border border-line bg-panel sm:aspect-[5/4] lg:aspect-square">
        <p className="type-data animate-pulse">Loading viewport</p>
      </div>
    ),
  },
);

/**
 * The landing hero.
 *
 * This is the real viewer component the editor uses, loading a real GLB from
 * the real engine. A marketing page for a 3D tool that shows a rendered still
 * is making a claim it is not demonstrating; this one demonstrates it.
 */
export function HeroViewport() {
  return (
    <figure className="animate-rise relative" style={{ animationDelay: "120ms" }}>
      <div className="relative rounded-[4px] border border-line bg-panel p-1.5">
        {/* Window chrome, in the idiom of a 3D application's viewport tab. */}
        <div className="flex items-center justify-between px-2 py-1.5">
          <div className="flex items-center gap-2">
            <span className="type-data">Viewport</span>
            <Badge tone="accent">T-pose</Badge>
          </div>
          <span className="type-data hidden sm:block">Drag to orbit</span>
        </div>

        <AvatarViewer
          src="/api/demo-avatar"
          className="aspect-[4/5] w-full sm:aspect-[5/4] lg:aspect-square"
          reveal
          autoRotate
          height={1.78}
        />
      </div>

      <figcaption className="sr-only">
        A 3D avatar generated by Incarnatrun, shown in a T-pose. Drag to orbit the
        camera.
      </figcaption>

      {/* The single accent glow on the page, anchoring the hero. */}
      <div
        className="pointer-events-none absolute -inset-8 -z-10 opacity-40 blur-3xl"
        style={{
          background:
            "radial-gradient(60% 50% at 50% 45%, color-mix(in oklab, var(--beam) 45%, transparent), transparent 70%)",
        }}
        aria-hidden
      />
    </figure>
  );
}
